#!/bin/bash

if [[ -d ../shared_srcs ]]; then
    echo "Updating sources..."
    cd ../shared_srcs
    git pull
    cd ../${build_number}
else
    echo "Cloning sources..."
    git clone https://github.com/tomsksoft-llc/ci-py-lib.git ../shared_srcs
fi

mkdir artifacts

echo "Running build script..."

. $cis_base_dir/jobs/$job_name/shared_srcs/.tscis/build.sh

echo "Packing artifacts..."

full_version=$( python3 build/lib-utils/util_sample.py -v )

VER="$full_version.$build_number"

cd $cis_base_dir/jobs/$job_name/$build_number/artifacts

echo $VER > build_version.txt

tar -czf ../artifacts.tgz *

echo "Sending emails..."

URL="cis.tomsksoft:$cis_base_dir/jobs/$job_name/$build_number/artifacts"

MAILS=$( $cis_base_dir/core/$getvalue mails )

if [ -z "$MAILS" ]
then
  MAILS=$( cat "$cis_base_dir/jobs/$job_name/../default_mails" )
fi

for MAIL in $MAILS; do
    printf "You can get it here: $URL\nBuild version: $VER" | mail -s "New pythonlibs build" $MAIL
done
