#!/bin/bash

git clone https://github.com/tomsksoft-llc/ci-py-lib.git src

cd src

cp lib-utils/lib_config.py.sample tests/lib_config.py

python3.7 -m pip install --user -r lib-utils/requirements.txt

cd tests

sed -i'' -e 's/PYTHON2 = \x27python\x27/PYTHON2 = \x27python2\x27/g; s/PYTHON3 = \x27python\x27/PYTHON3 = \x27python3.7\x27/g' lib_config.py

python3.7 lib_full_test.py

if [ $? -eq 0 ]
then
  echo "Tests finished successfully"
else
  echo "Tests failed"
  exit 1
fi

cd ../lib-utils

full_version=$( python3.7 util_sample.py -v )

cd ..

mkdir $cis_base_dir/jobs/$job_name/$build_number/artifacts

cp lib-utils/* $cis_base_dir/jobs/$job_name/$build_number/artifacts

VER="$full_version.$build_number"
echo $VER > $cis_base_dir/jobs/$job_name/$build_number/artifacts/build_version.txt

cd $cis_base_dir/jobs/$job_name/$build_number/artifacts

tar -czf ../artifacts.tgz *

URL="cis.tomsksoft:$cis_base_dir/jobs/$job_name/$build_number/artifacts"

MAILS=$( $cis_base_dir/core/$getvalue mails )

if [ -z "$MAILS" ]
then
  MAILS=$( cat "$cis_base_dir/jobs/$job_name/../default_mails" )
fi

for MAIL in $MAILS; do
    printf "You can get it here: $URL\nBuild version: $VER" | mail -s "New pythonlibs build" $MAIL
done
