#!/bin/bash

if [[ -d ../shared_srcs ]]; then
    echo "Updating sources..."
    cd ../shared_srcs
    git pull
    cd ../${build_number}
else
    echo "Cloning sources..."
    git clone https://github.com/tomsksoft-llc/cis1-core-native.git ../shared_srcs
fi

full_version=$( cat ../shared_srcs/version.txt )

source $cis_base_dir/jobs/$job_name/../setup_env.sh

mkdir artifacts

echo "Running build script..."

. $cis_base_dir/jobs/$job_name/shared_srcs/.tscis/build.sh

echo "Packing artigacts..."

cd $cis_base_dir/jobs/$job_name/$build_number/artifacts

VER="$full_version.$build_number"

echo $VER > $cis_base_dir/jobs/$job_name/$build_number/artifacts/build_version.txt

tar -czf ../artifacts.tgz *

echo "Sending emails..."

URL="cis.tomsksoft:$cis_base_dir/jobs/$job_name/$build_number/artifacts"

MAILS=$( $cis_base_dir/core/$getvalue mails )

if [ -z "$MAILS" ]
then
  MAILS=$( cat "$cis_base_dir/jobs/$job_name/../default_mails" )
fi

for MAIL in $MAILS; do
    printf "You can get it here: $URL\nBuild version: $VER" | mail -s "New cis core build" $MAIL
done
